export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const MODAL_REQUEST_SHOW = "MODAL_REQUEST_SHOW";
export const MODAL_REQUEST_HIDE = "MODAL_REQUEST_HIDE";
export const MODAL_ABOUT_SHOW = "MODAL_ABOUT_SHOW";
export const MODAL_ABOUT_HIDE = "MODAL_ABOUT_HIDE";